services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:  
      SPRING_PROFILES_ACTIVE: docker
    ports:  
      - 80:80

  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080


volumes:
  postgres_data:
  redis_data:
