services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: gonggu_db
      MYSQL_USER: gonggu
      MYSQL_ROOT_PASSWORD: gonggu
      MYSQL_PASSWORD: gonggu
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:  
      - 80:80

  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:  
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    platform: linux/amd64


volumes:
  mysql_data:
  redis_data:
