spring:
  application:
    name: backend

  profiles:
    active: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[default_batch_fetch_size]": 500
        "[highlight_sql]": true

fin-open:
  member-id: novelss5573@gmail.com
  api:
    base-url: https://finopenapi.ssafy.io/ssafy/api/v1/

image:
  path: classpath:static/images/


account:
  starter:
    type-unique-no: 088-1-a4827963282942
  flex:
    type-unique-no: 088-1-982fe078d3464b

