spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gonggu_db
    username: gonggu
    password: gonggu
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379